import {ApplicationData} from './state.interface';

export const initialState: ApplicationData = {
  date: new Date(),
  binNumber: '',
  commissioneRate: '',
  division: '',
  subDivision: '',
  circle: '',
  shopName: '',
  brandName: '',
  areaOrshoppingMall: '',
  businessRegisteredAddress: '',
  outletAddress: '',
  nid: '',
  name: '',
  mobile: '',
  email: '',
  startDate: new Date(),
  category: '',
  subCategory: '',
  numberOfOutlet: '',
  numberOfCounter: '',
  differentBin: '',
  transactionType: '',
  posSoftwareProvider: '',
  nrbApproved: '',
  thirdPartyName: '',
  monthlyAverageSales: '',
  monthlyAverageCustomer: '',
  onlineSaleAvailable: '',
  onlineSaleParcent: '',
  onlineOrderMode: '',
  productInfo: '',
  productName: '',
  productUnit: '',
  unitPrice: '',
  vatParcent: '',
  sdPercent: '',
  priceIncludingVat: '',
  priceExcludingVat: '',
  stockKeeping: '',
  posSoftware: '',
  posPrinter: '',
  pcOrLaptop: '',
  mushak: '',
  router: '',
  networking: '',
  surveillance: '',
  mobileOperator: '',
  operatorCoverage: '',
  shopPic: null,
  binCertificate: null,
  itemList: [],
};
